<a href="https://colab.research.google.com/github/CesarVh21/Algebra/blob/main/Libro_Semestral_de_Algebra_Lineal.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Matrices

In [ ]:
# Matrices

## Nula
## Matriz cuyos elementos son cero

\begin{bmatrix}
0 & 0\\
0 & 0
\end{bmatrix}

## Identidad

Si $a_{ij}$ = 0 , $\forall_{ij} \neq j \ \land $ $a_{ij}$ = 1 , $\forall_{ij} = j$

## Entonces A se llama I

Ej:

\begin{bmatrix}
1 & 0 & 0\\
0 & 1 & 0\\
0 & 0 & 1
\end{bmatrix}

## Matriz Diagonal

$a_{ij}$ = 0 , $\forall_{i} \neq j$
\begin{bmatrix}
0 & 0 & 0\\
0 & 2 & 0\\
0 & 0 & 1
\end{bmatrix}

## Matriz Triangulo Superior

Si $a_{ij} = 0, \forall_{i} > j $

Ej:

\begin{bmatrix}
1 & 3 & 2\\
0 & 2 & 4\\
0 & 0 & 1\\
\end{bmatrix}

## Matriz Triangulo Inferior

Si $a_{ij} = 0, \forall_{i} < j$

\begin{bmatrix}
1 & 0 & 0\\
5 & 7 & 0\\
7 & 6 & 2
\end{bmatrix}

## Matriz Simétrica

 ## Si $A = A^T$ entonces $A$ se llama simétrica

Ej:
$A=$
$\begin{bmatrix}
1 & 2\\
2 & 7
\end{bmatrix}$


$A^T=$
$\begin{bmatrix}
1 & 2\\
2 & 7
\end {bmatrix}$

 # Ejercicio de Matrices

In [ ]:
import numpy as np

# Generar dos matrices diagonales aleatorias

diagonal_a = np.diag(np.random.randint(1, 10, size=5))

diagonal_b = np.diag(np.random.randint(1, 10, size=5))

# Calcular el producto de las matrices diagonales

producto = np.dot(diagonal_a, diagonal_b)

print("Matriz A:")

print(diagonal_a)

print("Matriz B:")

print(diagonal_b)

print("Producto de las matrices:")

print(producto)


# Verificar si el producto es una matriz triangular superior

es_triangular_superior = np.allclose(np.triu(producto), producto)

print("Es una matriz triangular superior:", es_triangular_superior)

import numpy as np

# Generar dos matrices diagonales aleatorias

diagonal_a = np.diag(np.random.randint(1, 10, size=5))

diagonal_b = np.diag(np.random.randint(1, 10, size=5))

# Calcular el producto de las matrices diagonales

producto = np.dot(diagonal_a, diagonal_b)

print("Matriz A:")

print(diagonal_a)

print("Matriz B:")

print(diagonal_b)

print("Producto de las matrices:")

print(producto)

# Verificar si el producto es una matriz triangular superior

es_triangular_superior = np.allclose(np.triu(producto), producto)

print("Es una matriz triangular superior:", es_triangular_superior)

Matriz A:
[[1 0 0 0 0]
 [0 9 0 0 0]
 [0 0 9 0 0]
 [0 0 0 6 0]
 [0 0 0 0 4]]

Matriz B:

[[1 0 0 0 0]
 [0 3 0 0 0]
 [0 0 4 0 0]
 [0 0 0 4 0]
 [0 0 0 0 4]]

Producto de las matrices:

[[ 1 0 0 0 0]
 [ 0 27 0 0 0]
 [ 0 0 36 0 0]
 [ 0 0 0 24 0]
 [ 0 0 0 0 16]]
Es una matriz triangular superior: True

# Determinantes


In [ ]:
import numpy as np

# Definir una matriz de ejemplo

matriz = np.array([[1, 2, 3],
                   
[4, 5, 6],
                   
[7, 8, 9]])

# Calcular el determinante

determinante = np.linalg.det(matriz)

# Imprimir el resultado

print("El determinante de la matriz es:", determinante)

DETERMINANTES

import numpy as np

# Definir una matriz de ejemplo

matriz = np.array([[1, 2, 3],
                   
[4, 5, 6],
                   
[7, 8, 9]])
# Calcular el determinante

determinante = np.linalg.det(matriz)

# Imprimir el resultado

print("El determinante de la matriz es:", determinante)

El determinante de la matriz es: 0.0


# Factorizacion LU

In [ ]:
import numpy as np

from scipy.linalg import lu

# Definir la matriz

matriz = np.array([[4, 3, 1],
                   
[6, 9, 3],
                   
[2, 4, 8]])

# Aplicar la descomposición LU

P, L, U = lu(matriz)

# Imprimir la matriz L

print("Matriz L:")

print(L)

print()

# Imprimir la matriz U

print("Matriz U:")

print(U)

print()

# Imprimir la matriz P

print("Matriz P:")

print(P)

print()

import numpy as np

from scipy.linalg import lu

# Definir la matriz

matriz = np.array([[4, 3, 1],
                   
[6, 9, 3],
                   
[2, 4, 8]])
# Aplicar la descomposición LU

P, L, U = lu(matriz)

# Imprimir la matriz L

print("Matriz L:")

print(L)

print()

# Imprimir la matriz U

print("Matriz U:")

print(U)

print()

# Imprimir la matriz P

print("Matriz P:")

print(P)

print()

Matriz L:

[[ 1. 0. 0. ]
 
 [ 0.66666667 1. 0. ]

 [ 0.33333333 -0.33333333 1. ]]

Matriz U:

[[ 6. 9. 3. ]
 
 [ 0. -3. -1. ]

 [ 0. 0. 6.66666667]]

Matriz P:

[[0. 1. 0.]
 
 [1. 0. 0.]
 
 [0. 0. 1.]]

# Ortogonalizacion y Ortonormalizacion 

In [ ]:
# Ortogonalización y Ortonormalización

## Proceso de Gram-Schmidt

--Explicación--

# Ejercicios
a) Determine si los siguientes conjuntos de vectores en $R^n$ es ortogonal, si es ortogonal determine si es también ortonormal y determine si es base para $R^n$

$1) v_1 = \{(2,-4),(2,1)\}$

$2) v_2 = \{(3,2),(-4,-6)\}$

$3) v_3 = \{(4,-1,1),(-1,0,4),(-4,-17,-1)\}$

b)En los siguientes ejercicios use el proceso de $\textbf{Gram-Schmidt}$ para transformar la base dada para $R^n$ en una base ortonormal.

$1) v_1 = \{(3,4),(1,0)\}$

$2) v_2 = \{(0,1),(-4,-8)\}$

$3) v_3 = \{(1,-2,-2),(-2,2,1),(2,-1,2)\}$

# Independencia Lineal 

## Definición
Sea $S = \{\textbf{v}_1, \textbf{v}_2, ...., \textbf{v}_n \}$ un conjunto no vacío de vectores. 

a) Suponga que:

$ \alpha_1 \textbf{v}_1 + \alpha_2 \textbf{v}_2+......+\alpha_2 \textbf{v}_n  = \textbf{0}$ 

implica que $ \alpha_1 = \alpha_2 = ....=\alpha_n$. Se dice entonces que $\textbf{S}$ es ***linealmente independiente***

b) Un conjunto que no es linealmente independiente se llama ***linealmente dependiente***; análogamente,  $\textbf{S}$ es linealmente dependiente si y solo si hay escalares $ \alpha_1 = \alpha_2 = ....=\alpha_n$ **NO** todos cero, tales que

$ \alpha_1 \textbf{v}_1 + \alpha_2 \textbf{v}_2+......+\alpha_2 \textbf{v}_n  = \textbf{0}$ 

## Python Code
```python 
#Importamos la libreria numpy
import numpy as np

# Los vectores linealmente independientes (En este ejemplo, tenemos 3 vectores en un espacio 3-dimensional)
v1 = np.array([1, 2, 2])
v2 = np.array([4, 5, 6])
v3 = np.array([7, 8, 9])

# El vector que queremos expresar como una combinación lineal de vectores independientes ((0,0,0))
target = np.array([0, 0, 0])

#Creamos una matriz con los vectores independientes como columnas
matrix = np.column_stack((v1, v2, v3))

#Resolvemos el sistema lineal para encontrar los coeficientes
coefficients = np.linalg.solve(matrix, target)

print("Coefficients:", coefficients)
```


In [ ]:
#Importamos la libreria numpy
import numpy as np

# Los vectores linealmente independientes (En este ejemplo, tenemos 3 vectores en un espacio 3-dimensional)
v1 = np.array([1, 2, 2])
v2 = np.array([4, 5, 6])
v3 = np.array([7, 8, 9])

# El vector que queremos expresar como una combinación lineal de vectores independientes ((0,0,0))
target = np.array([0, 0, 0])

#Creamos una matriz con los vectores independientes como columnas
matrix = np.column_stack((v1, v2, v3))

#Resolvemos el sistema lineal para encontrar los coeficientes
coefficients = np.linalg.solve(matrix, target)

print("Coefficients:", coefficients)



Coefficients: [ 0.  0. -0.]


# Linealmente Independiente

In [ ]:
import numpy as np

# Definir un conjunto de vectores de ejemplo

vectors = np.array([[1, 2, 3],
                    
[4, 5, 6],
                    
[7, 8, 9]])

# Comprobar si el conjunto de vectores es linealmente dependiente

dependent = np.linalg.matrix_rank(vectors) < vectors.shape[0]

# Imprimir el resultado

if dependent:

print("El conjunto de vectores es linealmente dependiente.")

else:

print("El conjunto de vectores es linealmente independiente.")


import numpy as np

# Definir un conjunto de vectores de ejemplo

vectors = np.array([[1, 2, 3],
                    
[4, 5, 6],
                    

[7, 8, 9]])

# Comprobar si el conjunto de vectores es linealmente dependiente

dependent = np.linalg.matrix_rank(vectors) < vectors.shape[0]

# Imprimir el resultado

if dependent:

print("El conjunto de vectores es linealmente dependiente.")

else:

print("El conjunto de vectores es linealmente independiente.")



# Subespacios Vectoriales 

In [ ]:
import numpy as np

# Definir una matriz de ejemplo

matriz = np.array([[1, 2, 3],
                   
[4, 5, 6],
                   
0 [7, 8, 9]])

# Definir un vector de ejemplo

vector = np.array([1, 2, 3])

# Comprobar si el vector pertenece al subespacio generado por las columnas de la matriz

perteneciente = np.allclose(matriz @ vector, 0)

# Imprimir el resultado

if perteneciente:

print("El vector pertenece al subespacio generado por las columnas de la matriz.")

else:

print("El vector no pertenece al subespacio generado por las columnas de la matriz.")

import numpy as np

# Definir una matriz de ejemplo

matriz = np.array([[1, 2, 3],
                   
[4, 5, 6],
                   
0 [7, 8, 9]])

# Definir un vector de ejemplo

vector = np.array([1, 2, 3])

# Comprobar si el vector pertenece al subespacio generado por las columnas de la matriz

perteneciente = np.allclose(matriz @ vector, 0)

# Imprimir el resultado

if perteneciente:

print("El vector pertenece al subespacio generado por las columnas de la matriz.")

else:

print("El vector no pertenece al subespacio generado por las columnas de la matriz.")




# Transformaciones Lineales

In [ ]:
import numpy as np

def traslacion(x, y, tx, ty):


vector = np.array([x, y])

matriz_translacion = np.array([[1, 0, tx],
                               
[0, 1, ty],
                               
[0, 0, 1]])

resultado = matriz_translacion @ vector

return resultado[0], resultado[1]

# Ejemplo de uso

x = 2

y = 3

tx = 1

ty = 1

resultado = traslacion(x, y, tx, ty)

print(resultado)

import numpy as np

import matplotlib.pyplot as plt

# Definir los puntos originales

x = np.array([2, 4])

y = np.array([3, 1])

# Valores de traslación

tx = 3

ty = 2

# Aplicar la traslación a los puntos

x_trans = x + tx

y_trans = y + ty

# Crear la figura y los ejes

fig, ax = plt.subplots()

# Graficar los puntos originales y los puntos trasladados

ax.plot(x, y, 'ro', label='Puntos originales')

ax.plot(x_trans, y_trans, 'bo', label='Puntos trasladados')

# Establecer límites de los ejes

ax.set_xlim([0, 10])

ax.set_ylim([0, 10])

# Etiquetas de los ejes

ax.set_xlabel('Eje X')

ax.set_ylabel('Eje Y')





# Vectores Propios

In [ ]:
import numpy as np

# Definir la matriz

matriz = np.array([[2, -1],
                   
[4, 3]])

# Calcular los vectores propios y los valores propios

valores_propios, vectores_propios = np.linalg.eig(matriz)

# Imprimir los valores propios y los vectores propios

for i in range(len(valores_propios)):

print("Valor propio:", valores_propios[i])

print("Vector propio:", vectores_propios[:, i])

print()

import numpy as np

# Definir la matriz

matriz = np.array([[2, -1],
                   
[4, 3]])

# Calcular los vectores propios y los valores propios

valores_propios, vectores_propios = np.linalg.eig(matriz)

# Imprimir los valores propios y los vectores propios

for i in range(len(valores_propios)):

print("Valor propio:", valores_propios[i])

print("Vector propio:", vectores_propios[:, i])

print()

Valor propio: (2.5+1.9364916731037083j)

Vector propio: [-0.1118034 +0.4330127j 0.89442719+0.j ]

Valor propio: (2.5-1.9364916731037083j)

Vector propio: [-0.1118034 -0.4330127j 0.89442719-0.j 